import { mdiPencilOutline } from "@mdi/js";
import {
  ListItemIcon,
  ListItemText,
  MenuItem,
  type MenuItemProps,
  styled,
  SvgIcon,
} from "@mui/material";
import { mergeProps } from "@react-aria/utils";
import { type MouseEventHandler } from "react";
import { FormattedMessage } from "react-intl";
import { useSearchParams } from "react-router";

import { usePlayerId } from "../../hooks/usePlayerId";

const MenuItemIcon = styled(ListItemIcon)({
  color: "inherit",
});

export const PlayerEditMenuItem = (props: MenuItemProps) => {
  const [, setSearchParams] = useSearchParams();

  const playerId = usePlayerId();

  const onClick: MouseEventHandler<HTMLButtonElement> = () => {
    setSearchParams((searchParams) => {
      searchParams.set("player", playerId);

      return searchParams;
    });
  };

  return (
    <MenuItem {...mergeProps({ onClick }, props)}>
      <MenuItemIcon>
        <SvgIcon>
          <path d={mdiPencilOutline} />
        </SvgIcon>
      </MenuItemIcon>
      <ListItemText>
        <FormattedMessage
          defaultMessage="Edit"
          // eslint-disable-next-line formatjs/enforce-id -- will migrate to autogenerated ids
          id="player.list.edit"
        />
      </ListItemText>
    </MenuItem>
  );
};
