import { mdiClose } from "@mdi/js";
import { type IconButtonProps, SvgIcon, Tooltip } from "@mui/material";
import { useIntl } from "react-intl";

import TopIconButton from "../../components/TopIconButton";

export const CloseIconButton = (props: IconButtonProps) => {
  const intl = useIntl();

  return (
    <Tooltip
      title={intl.formatMessage({
        defaultMessage: "Cancel",
        // eslint-disable-next-line formatjs/enforce-id -- will migrate to autogenerated ids
        id: "button.cancel",
      })}
    >
      <TopIconButton {...props}>
        <SvgIcon>
          <path d={mdiClose} />
        </SvgIcon>
      </TopIconButton>
    </Tooltip>
  );
};
