append_commit_message: false
commit_message: "chore(l10n): new translations %original_file_name% (%language%)"
files:
  - source: /packages/site/domains/l10n/messages/en.json
    translation: /%original_path%/%locale%.json
    excluded_target_languages:
      - be
      - cs
      - da
      - el
      - es-ES
      - fi
      - fr
      - he
      - hu
      - hy-AM
      - it
      - nb
      - nl
      - pl
      - pt-BR
      - pt-PT
      - sk
      - tr
      - uk
  - source: /packages/web/l10n/en.json
    translation: /%original_path%/%locale%.json
  - source: /packages/web/src/templates/data/en.json
    translation: /%original_path%/%locale%.json
    excluded_target_languages:
      - be
      - cs
      - da
      - de
      - el
      - es-ES
      - fi
      - fr
      - he
      - hu
      - hy-AM
      - it
      - nb
      - nl
      - pl
      - pt-BR
      - pt-PT
      - sk
      - tr
      - uk
pull_request_title: "chore(l10n): new Crowdin updates"
