import { mdiPlus } from "@mdi/js";
import { type FabProps, SvgIcon } from "@mui/material";
import { useCallback } from "react";
import { useIntl } from "react-intl";
import { useSearchParams } from "react-router";

import ScreenFab from "../../ScreenFab";

const PlayerAddButton = (props: FabProps) => {
  const intl = useIntl();
  const [, setSearchParams] = useSearchParams();

  const onClick = useCallback(() => {
    setSearchParams((searchParams) => {
      searchParams.set("player", "");

      return searchParams;
    });
  }, [setSearchParams]);

  return (
    <ScreenFab
      aria-label={intl.formatMessage({
        defaultMessage: "Add",
        // eslint-disable-next-line formatjs/enforce-id -- will migrate to autogenerated ids
        id: "mainButton.label",
      })}
      onClick={onClick}
      {...props}
    >
      <SvgIcon>
        <path d={mdiPlus} />
      </SvgIcon>
    </ScreenFab>
  );
};

export default PlayerAddButton;
