export const FINISH_COMBAT = 'app/FINISH_COMBAT';
export const SET_COMBAT_HELPER = 'core/SET_COMBAT_HELPER';
export const SET_COMBAT_HELPER_BONUS = 'core/SET_COMBAT_HELPER_BONUS';
export const SET_COMBAT_PLAYER_BONUS = 'core/SET_COMBAT_PLAYER_BONUS';
export const START_COMBAT = 'core/START_COMBAT';
