import { useIntl } from "react-intl";

import { useGoBack } from "../../utils/location";
import BackButton from "../BackButton";
import { RouteScreenModal } from "../RouteScreenModal";
import SettingsList from "../SettingsList";
import Title from "../Title";
import TopAppBar from "../TopAppBar";

const SettingsDialog = () => {
  const intl = useIntl();

  const goBack = useGoBack();

  return (
    <RouteScreenModal path="/settings">
      <TopAppBar>
        <BackButton onClick={goBack} />
        <Title>
          {intl.formatMessage({
            defaultMessage: "Settings",
            // eslint-disable-next-line formatjs/enforce-id -- will migrate to autogenerated ids
            id: "settings",
          })}
        </Title>
      </TopAppBar>
      <SettingsList />
    </RouteScreenModal>
  );
};

export default SettingsDialog;
