import { DialogActions } from "@mui/material";
import { useIntl } from "react-intl";

import { useGoBack } from "../../utils/location";
import CancelButton from "../CancelButton";
import SubmitButton from "../SubmitButton";

import formId from "./formId";

export const PlayerDialogActions = () => {
  const intl = useIntl();

  const goBack = useGoBack();

  return (
    <DialogActions>
      <CancelButton onClick={goBack} />
      <SubmitButton form={formId}>
        {intl.formatMessage({
          defaultMessage: "Save",
          // eslint-disable-next-line formatjs/enforce-id -- will migrate to autogenerated ids
          id: "player.form.save",
        })}
      </SubmitButton>
    </DialogActions>
  );
};
