import { DialogTitle, Typography } from "@mui/material";
import { useState } from "react";
import { useIntl } from "react-intl";
import { useSearchParams } from "react-router";

import useDeletePlayers from "../../hooks/useDeletePlayers";
import { useGoBack } from "../../utils/location";

import AppBar from "./AppBar";
import { useFullScreen } from "./useFullScreen";

export const PlayerDialogTitle = () => {
  const intl = useIntl();
  const [searchParams] = useSearchParams();

  const fullScreen = useFullScreen();
  const goBack = useGoBack();
  const deletePlayers = useDeletePlayers();

  const [playerId] = useState(searchParams.get("player"));

  const title = playerId
    ? intl.formatMessage({
        defaultMessage: "Edit munchkin",
        // eslint-disable-next-line formatjs/enforce-id -- will migrate to autogenerated ids
        id: "player.form.titleEdit",
      })
    : intl.formatMessage({
        defaultMessage: "New munchkin",
        // eslint-disable-next-line formatjs/enforce-id -- will migrate to autogenerated ids
        id: "player.form.title",
      });

  return (
    <DialogTitle
      sx={(theme) => ({
        alignItems: "center",
        display: "flex",
        justifyContent: "space-between",

        [theme.breakpoints.down("lg")]: {
          display: "block",
          padding: 0,
        },
      })}
    >
      {fullScreen ? (
        <AppBar
          onCancel={goBack}
          onDelete={
            playerId
              ? async () => {
                  deletePlayers([playerId]);
                  await goBack();
                }
              : undefined
          }
          title={title}
        />
      ) : (
        <Typography component="span" noWrap variant="h6">
          {title}
        </Typography>
      )}
    </DialogTitle>
  );
};
