import { mdiGenderFemale, mdiGenderMale } from "@mdi/js";
import {
  FormControl,
  FormControlLabel,
  FormLabel,
  Grid,
  InputLabel,
  OutlinedInput,
  Radio,
  RadioGroup,
  SvgIcon,
} from "@mui/material";
import { type ComponentProps, type FormEvent, useMemo, useState } from "react";
import { useIntl } from "react-intl";
import { useSearchParams } from "react-router";

import { type Player, Sex } from "../../domains/player";
import { addPlayerToList } from "../../ducks/playerList";
import { addPlayer, updatePlayer } from "../../ducks/players";
import usePresentSelector from "../../hooks/usePresentSelector";
import { useAppDispatch } from "../../store";
import { type AvailableColor } from "../../utils/availableColors";
import createPlayer from "../../utils/createPlayer";
import getRandomMaterialColor from "../../utils/getRandomMaterialColor";
import { useGoBack } from "../../utils/location";
import shallowEqual from "../../utils/shallowEqual";

import ColorPicker from "./ColorPicker";
import formId from "./formId";

const nameId = "player-form-name";

export const PlayerForm = (props: ComponentProps<"form">) => {
  const intl = useIntl();
  const [searchParams] = useSearchParams();

  const dispatch = useAppDispatch();
  const goBack = useGoBack();

  const players = usePresentSelector((state) => state.players);

  // eslint-disable-next-line formatjs/enforce-id -- will migrate to autogenerated ids
  const nameLabel = intl.formatMessage({
    defaultMessage: "Name",
    id: "player.form.namePlaceholder",
  });

  const queryPlayer = searchParams.get("player");

  const [editPlayer] = useState(queryPlayer ? players[queryPlayer] : undefined);

  const randomColor = useMemo(
    () =>
      getRandomMaterialColor(
        Object.values(players)
          .map((player) => player.color)
          .filter((color): color is AvailableColor => color !== undefined),
      ),
    [players],
  );

  const [playerColor] = useState(editPlayer?.color ?? randomColor);

  const onSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    const formData = new FormData(event.target as HTMLFormElement);

    const formValues: Partial<Player> = Object.fromEntries(formData);

    if (!formValues.name?.trim()) {
      await goBack();

      return;
    }

    if (editPlayer) {
      const player: Player = {
        ...editPlayer,
        ...formValues,
      };

      if (shallowEqual(editPlayer, player)) {
        await goBack();

        return;
      }

      dispatch(updatePlayer(player));
    } else {
      const player = createPlayer(formValues);

      dispatch(addPlayer(player));
      dispatch(addPlayerToList(player.id));
    }

    await goBack();
  };

  return (
    <form id={formId} onSubmit={onSubmit} {...props}>
      <FormControl fullWidth margin="normal">
        <InputLabel htmlFor={nameId}>{nameLabel}</InputLabel>
        <OutlinedInput
          autoFocus={!editPlayer}
          defaultValue={editPlayer?.name}
          id={nameId}
          label={nameLabel}
          name="name"
        />
      </FormControl>

      <Grid container>
        <Grid size={6}>
          <FormControl component="fieldset" margin="normal">
            <FormLabel component="legend">
              {
                // eslint-disable-next-line formatjs/enforce-id -- will migrate to autogenerated ids
                intl.formatMessage({
                  defaultMessage: "Sex",
                  id: "player.form.sex",
                })
              }
            </FormLabel>
            <RadioGroup defaultValue={editPlayer?.sex ?? Sex.Male} name="sex">
              <FormControlLabel
                control={<Radio color="primary" />}
                label={
                  <SvgIcon sx={{ verticalAlign: "middle" }}>
                    <path d={mdiGenderMale} />
                  </SvgIcon>
                }
                value={Sex.Male}
              />
              <FormControlLabel
                control={<Radio color="primary" />}
                label={
                  <SvgIcon sx={{ verticalAlign: "middle" }}>
                    <path d={mdiGenderFemale} />
                  </SvgIcon>
                }
                value={Sex.Female}
              />
            </RadioGroup>
          </FormControl>
        </Grid>

        <Grid size={6}>
          <FormControl margin="normal">
            <FormLabel>
              {
                // eslint-disable-next-line formatjs/enforce-id -- will migrate to autogenerated ids
                intl.formatMessage({
                  defaultMessage: "Color",
                  id: "player.form.color",
                })
              }
            </FormLabel>
            <ColorPicker defaultValue={playerColor} name="color" />
          </FormControl>
        </Grid>
      </Grid>
    </form>
  );
};
