import { Button, DialogActions } from "@mui/material";
import { useState } from "react";
import { useIntl } from "react-intl";
import { useSearchParams } from "react-router";

import useDeletePlayers from "../../hooks/useDeletePlayers";
import { useGoBack } from "../../utils/location";
import CancelButton from "../CancelButton";
import SubmitButton from "../SubmitButton";

import formId from "./formId";

export const PlayerDialogActions = () => {
  const intl = useIntl();
  const [searchParams] = useSearchParams();

  const deletePlayers = useDeletePlayers();
  const goBack = useGoBack();

  const [playerId] = useState(searchParams.get("player"));

  return (
    <DialogActions>
      {playerId && (
        <Button
          onClick={async () => {
            deletePlayers([playerId]);
            await goBack();
          }}
          sx={{ marginRight: "auto" }}
        >
          {
            // eslint-disable-next-line formatjs/enforce-id -- will migrate to autogenerated ids
            intl.formatMessage({
              defaultMessage: "Delete",
              id: "player.form.delete",
            })
          }
        </Button>
      )}
      <CancelButton onClick={goBack} />
      <SubmitButton form={formId}>
        {
          // eslint-disable-next-line formatjs/enforce-id -- will migrate to autogenerated ids
          intl.formatMessage({
            defaultMessage: "Save",
            id: "player.form.save",
          })
        }
      </SubmitButton>
    </DialogActions>
  );
};
