import {
  Button,
  Fade,
  Snackbar,
  type SnackbarCloseReason,
  useMediaQuery,
  useTheme,
} from "@mui/material";
import { FormattedMessage } from "react-intl";
import { ActionCreators } from "redux-undo";

import { useAppDispatch, useAppSelector } from "../../store";
import { useUndo } from "../UndoProvider";

const UndoSnackbar = () => {
  const dispatch = useAppDispatch();
  const theme = useTheme();

  const mdDown = useMediaQuery(theme.breakpoints.down("md"));

  const open = useAppSelector((state) => state.past.length > 0);

  const onClose = (event: unknown, reason: "undo" | SnackbarCloseReason) => {
    if (reason === "undo") {
      dispatch(ActionCreators.undo());
    }

    dispatch(ActionCreators.clearHistory());
  };

  const { message, setMessage } = useUndo();

  return (
    <Snackbar
      action={
        <Button color="secondary" onClick={(event) => onClose(event, "undo")}>
          {/* eslint-disable-next-line formatjs/enforce-id -- will migrate to autogenerated ids */}
          <FormattedMessage defaultMessage="Undo" id="undo" />
        </Button>
      }
      autoHideDuration={8000}
      message={message}
      onClose={onClose}
      open={open}
      slotProps={{
        transition: {
          onExited: () => setMessage(null),
        },
      }}
      slots={{
        transition: mdDown ? Fade : undefined,
      }}
      sx={(theme) => ({
        bottom: {
          sm: `calc(${theme.spacing(3)} + var(--inset-bottom))`,
          xs: `calc(${theme.spacing(3)} + 56px + var(--inset-bottom))`,
        },
      })}
    />
  );
};

export default UndoSnackbar;
