import { mdiAccountPlusOutline, mdiEmoticonDevilOutline } from "@mdi/js";
import {
  Backdrop,
  SpeedDial,
  SpeedDialAction,
  type SpeedDialActionProps,
  SpeedDialIcon,
  SvgIcon,
} from "@mui/material";
import { FormattedMessage } from "react-intl";
import { useSearchParams } from "react-router";

import { addMonster } from "../../../ducks/monsters";
import usePresentSelector from "../../../hooks/usePresentSelector";
import { useAppDispatch } from "../../../store";
import createMonster from "../../../utils/createMonster";
import { useGoBack } from "../../../utils/location";

const CombatHelperButton = () => {
  const dispatch = useAppDispatch();
  const [searchParams, setSearchParams] = useSearchParams();

  const goBack = useGoBack();
  const helperId = usePresentSelector((state) => state.combat.helperId);
  const hasOtherPlayers = usePresentSelector(
    (state) => state.playerList.length > 1,
  );
  const helper = !helperId && hasOtherPlayers;
  const open = searchParams.get("add") === "";

  const onAdd = () => {
    setSearchParams((searchParams) => {
      searchParams.set("add", "");

      return searchParams;
    });
  };

  const onHelperClick: SpeedDialActionProps["onClick"] = (event) => {
    event.stopPropagation();

    setSearchParams(
      (searchParams) => {
        searchParams.set("add", "helper");

        return searchParams;
      },
      {
        replace: true,
      },
    );
  };

  const onMonsterAdd = () => dispatch(addMonster(createMonster()));

  const onMonsterClick: SpeedDialActionProps["onClick"] = (event) => {
    event.stopPropagation();
    onMonsterAdd();
    void goBack();
  };

  const onSpeedDialClick = async () => {
    if (open) {
      await goBack();
    } else if (helper) {
      onAdd();
    } else {
      onMonsterAdd();
    }
  };

  return (
    <>
      <Backdrop
        onClick={goBack}
        open={open}
        sx={{
          zIndex: 1,
        }}
      />

      <SpeedDial
        ariaLabel=" "
        icon={
          helper ? (
            <SpeedDialIcon />
          ) : (
            <SvgIcon>
              <path d={mdiEmoticonDevilOutline} />
            </SvgIcon>
          )
        }
        onClick={onSpeedDialClick}
        open={open}
        slotProps={{
          transition: {
            appear: false,
          },
        }}
        sx={[
          (theme) => ({
            bottom: {
              sm: `calc(${theme.spacing(3)} + var(--inset-bottom))`,
              xs: `calc(${theme.spacing(2)} + var(--inset-bottom))`,
            },
            position: "fixed",
            zIndex: 2,
          }),
          (theme) => ({
            '[dir="ltr"] &': {
              left: "auto /*! @noflip */",
              right: {
                sm: `calc(${theme.spacing(3)} + var(--inset-right)) /*! @noflip */`,
                xs: `calc(${theme.spacing(2)} + var(--inset-right)) /*! @noflip */`,
              },
            },
            '[dir="rtl"] &': {
              left: {
                sm: `calc(${theme.spacing(3)} + var(--inset-left)) /*! @noflip */`,
                xs: `calc(${theme.spacing(2)} + var(--inset-left)) /*! @noflip */`,
              },
              right: "auto /*! @noflip */",
            },
          }),
        ]}
      >
        <SpeedDialAction
          icon={
            <SvgIcon>
              <path d={mdiEmoticonDevilOutline} />
            </SvgIcon>
          }
          onClick={onMonsterClick}
          slotProps={{
            tooltip: {
              title: (
                <FormattedMessage
                  defaultMessage="Monster"
                  // eslint-disable-next-line formatjs/enforce-id -- will migrate to autogenerated ids
                  id="combat.add.monster"
                />
              ),
            },
          }}
        />
        <SpeedDialAction
          icon={
            <SvgIcon>
              <path d={mdiAccountPlusOutline} />
            </SvgIcon>
          }
          onClick={onHelperClick}
          slotProps={{
            tooltip: {
              title: (
                <FormattedMessage
                  defaultMessage="Helper"
                  // eslint-disable-next-line formatjs/enforce-id -- will migrate to autogenerated ids
                  id="combat.add.helper"
                />
              ),
            },
          }}
        />
      </SpeedDial>
    </>
  );
};

export default CombatHelperButton;
