import {
  mdiMenuDown as decrementIcon,
  mdiMenuUp as incrementIcon,
} from "@mdi/js";
import {
  Box,
  type BoxProps,
  IconButton,
  SvgIcon,
  type Theme,
} from "@mui/material";
import { usePress } from "@react-aria/interactions";
import { type SpinButtonProps, useSpinButton } from "@react-aria/spinbutton";
import { type FC, type ReactNode } from "react";
import { defineMessages, FormattedNumber } from "react-intl";

import CounterLabel from "./Label";

export const counterMessages = defineMessages({
  gear: {
    defaultMessage: "Gear",
    // eslint-disable-next-line formatjs/enforce-id -- will migrate to autogenerated ids
    id: "counter.gear",
  },
  level: {
    defaultMessage: "Level",
    // eslint-disable-next-line formatjs/enforce-id -- will migrate to autogenerated ids
    id: "counter.level",
  },
  modifier: {
    defaultMessage: "Modifier",
    // eslint-disable-next-line formatjs/enforce-id -- will migrate to autogenerated ids
    id: "counter.modifier",
  },
  strength: {
    defaultMessage: "Strength",
    // eslint-disable-next-line formatjs/enforce-id -- will migrate to autogenerated ids
    id: "counter.strength",
  },
});

type CounterProps = {
  onDecrement: () => void;
  onIncrement: () => void;
  title: ReactNode;
  value: number;
} & Omit<BoxProps, "title"> &
  Pick<SpinButtonProps, "maxValue" | "minValue">;

const Counter: FC<CounterProps> = ({
  maxValue,
  minValue,
  onDecrement,
  onIncrement,
  sx = [],
  title,
  value,
  ...props
}) => {
  const { decrementButtonProps, incrementButtonProps, spinButtonProps } =
    useSpinButton({
      maxValue,
      minValue,
      onDecrement,
      onIncrement,
      value,
    });

  const decrementDisabled = minValue !== undefined && value <= minValue;

  const { pressProps: decrementButtonPressProps } = usePress({
    ...decrementButtonProps,
    isDisabled: decrementDisabled,
  });

  const incrementDisabled = maxValue !== undefined && value >= maxValue;

  const { pressProps: incrementButtonPressProps } = usePress({
    ...incrementButtonProps,
    isDisabled: incrementDisabled,
  });

  return (
    <Box
      sx={[
        {
          alignItems: "center",
          display: "flex",
          flexDirection: "column",
        },
        ...[sx].flat(),
      ]}
      {...props}
    >
      <CounterLabel
        sx={{
          fontSize: "1.5rem",
          textAlign: "center",
          width: "100%",
        }}
      >
        {title}
      </CounterLabel>

      <Box
        {...spinButtonProps}
        sx={{
          color: "text.primary",
          fontFamily: (theme: Theme) =>
            `Munchkin, ${String(theme.typography.fontFamily)}`,
          fontSize: "2.25rem",
        }}
      >
        <FormattedNumber value={value} />
      </Box>

      <Box
        sx={{
          display: "flex",
          justifyContent: "space-between",
          width: "120px",
        }}
      >
        <IconButton
          {...decrementButtonPressProps}
          data-screenshots="decrement-button"
          disabled={decrementDisabled}
          sx={{
            fontSize: "3rem",
            padding: 0,
          }}
        >
          <SvgIcon
            sx={{
              fontSize: "inherit",
            }}
          >
            <path d={decrementIcon} />
          </SvgIcon>
        </IconButton>

        <IconButton
          {...incrementButtonPressProps}
          data-screenshots="increment-button"
          disabled={incrementDisabled}
          sx={{
            fontSize: "3rem",
            padding: 0,
          }}
        >
          <SvgIcon
            sx={{
              fontSize: "inherit",
            }}
          >
            <path d={incrementIcon} />
          </SvgIcon>
        </IconButton>
      </Box>
    </Box>
  );
};

export default Counter;
