import { defineMessages } from "react-intl";

export default defineMessages<{
  readonly epic: {
    readonly maxLevel: number;
    readonly minLevel: number;
  };
  readonly label: {};
  readonly munchkin: {
    readonly maxLevel: number;
    readonly minLevel: number;
  };
  readonly none: {};
}>({
  epic: {
    defaultMessage: "Epic Munchkin ({minLevel, number} - {maxLevel, number})",
    // eslint-disable-next-line formatjs/enforce-id -- will migrate to autogenerated ids
    id: "levelLimit.epic",
  },
  label: {
    defaultMessage: "Level limit",
    // eslint-disable-next-line formatjs/enforce-id -- will migrate to autogenerated ids
    id: "levelLimit.label",
  },
  munchkin: {
    defaultMessage: "Munchkin ({minLevel, number} - {maxLevel, number})",
    // eslint-disable-next-line formatjs/enforce-id -- will migrate to autogenerated ids
    id: "levelLimit.munchkin",
  },
  none: {
    defaultMessage: "No limit",
    // eslint-disable-next-line formatjs/enforce-id -- will migrate to autogenerated ids
    id: "levelLimit.none",
  },
});
