import { defineMessages } from "react-intl";

export default defineMessages({
  epic: {
    defaultMessage: "Epic Munchkin ({minLevel} - {maxLevel})",
    // eslint-disable-next-line formatjs/enforce-id -- will migrate to autogenerated ids
    id: "levelLimit.epic",
  },
  label: {
    defaultMessage: "Level limit",
    // eslint-disable-next-line formatjs/enforce-id -- will migrate to autogenerated ids
    id: "levelLimit.label",
  },
  munchkin: {
    defaultMessage: "Munchkin ({minLevel} - {maxLevel})",
    // eslint-disable-next-line formatjs/enforce-id -- will migrate to autogenerated ids
    id: "levelLimit.munchkin",
  },
  none: {
    defaultMessage: "No limit",
    // eslint-disable-next-line formatjs/enforce-id -- will migrate to autogenerated ids
    id: "levelLimit.none",
  },
});
