import { defineMessages } from "react-intl";

// eslint-disable-next-line formatjs/enforce-id -- will migrate to autogenerated ids
export default defineMessages({
  color: {
    defaultMessage: "Color",
    id: "theme.color",
  },
  label: {
    defaultMessage: "Theme",
    id: "theme",
  },
  schemeAuto: {
    defaultMessage: "System Default",
    id: "themeDialog.auto",
  },
  schemeDark: {
    defaultMessage: "Dark",
    id: "themeDialog.dark",
  },
  schemeLight: {
    defaultMessage: "Light",
    id: "themeDialog.light",
  },
});
