export const ADD_MONSTER = "core/ADD_MONSTER";
export const DECREMENT_MONSTER_BONUS = "core/DECREMENT_MONSTER_BONUS";
export const DECREMENT_MONSTER_LEVEL = "core/DECREMENT_MONSTER_LEVEL";
export const INCREMENT_MONSTER_BONUS = "core/INCREMENT_MONSTER_BONUS";
export const INCREMENT_MONSTER_LEVEL = "core/INCREMENT_MONSTER_LEVEL";
export const REMOVE_MONSTER = "core/REMOVE_MONSTER";
