name: Deploy App

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.4.0
        with:
          cache: "yarn"
          cache-dependency-path: "yarn.lock"
          node-version-file: ".nvmrc"

      - name: Install ⬇️
        env:
          HUSKY: 0
        run: yarn install --immutable

      - name: Compile locales 🔨
        run: yarn workspace @munchkin/web run i18n:compile

      - name: Get app version
        run: echo "VERSION=$(yarn run get-version)" >> $GITHUB_ENV

      - name: Check
        run: yarn check

      - name: Test
        run: yarn workspaces foreach --all run test

      - name: Build 🔨
        run: yarn workspaces foreach --from '@munchkin/{cordova,pwa}' --parallel --recursive run build

      - name: Create Sentry release
        uses: getsentry/action-release@5657c9e888b4e2cc85f4d29143ea4131fde4a73a # v3.6.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
          release: ${{ format('munchkin@{0}', env.VERSION) }}
          sourcemaps: "./packages/cordova/www ./packages/pwa/dist"

      - name: Deploy 🚀
        uses: FirebaseExtended/action-hosting-deploy@e2eda2e106cfa35cdbcf4ac9ddaf6c4756df2c8c # v0.10.0
        with:
          channelId: live
          entryPoint: packages/pwa
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_IZORG_MUNCHKIN }}
          projectId: izorg-munchkin
          repoToken: ${{ secrets.GITHUB_TOKEN }}
