name: Deploy App

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node.js
        uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # v7.1.0
        with:
          cache: "yarn"
          cache-dependency-path: "yarn.lock"
          node-version-file: ".nvmrc"

      - name: Install ⬇️
        env:
          HUSKY: 0
        run: |
          npm install -g corepack
          yarn install --immutable

      - name: Compile locales 🔨
        run: yarn workspace @munchkin/web run i18n:compile

      - name: Get app version
        run: echo "VERSION=$(yarn run get-version)" >> $GITHUB_ENV

      - name: Check
        run: yarn check

      - name: Test
        run: yarn workspaces foreach --all run test

      - name: Build 🔨
        run: yarn workspaces foreach --from '@munchkin/{cordova,pwa}' --parallel --recursive run build

      - name: Create Sentry release
        uses: getsentry/action-release@6fb9aeade7061441cf3864e34fbe11a1457ad7dc # v3.7.1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
          release: ${{ format('munchkin@{0}', env.VERSION) }}
          sourcemaps: "./packages/cordova/www ./packages/pwa/dist"

      - name: Deploy 🚀
        uses: FirebaseExtended/action-hosting-deploy@500ac625ca2dd40cbd15f7659af953801858032a # v0.11.0
        with:
          channelId: live
          entryPoint: packages/pwa
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_IZORG_MUNCHKIN }}
          projectId: izorg-munchkin
          repoToken: ${{ secrets.GITHUB_TOKEN }}
