name: Deploy App

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          cache: "yarn"
          cache-dependency-path: "yarn.lock"
          node-version-file: ".nvmrc"

      - name: Install ⬇️
        env:
          HUSKY: 0
        run: |
          npm install -g corepack
          yarn install --immutable

      - name: Compile locales 🔨
        run: yarn workspace @munchkin/web run i18n:compile

      - name: Get app version
        run: echo "VERSION=$(yarn run get-version)" >> $GITHUB_ENV

      - name: Check
        run: yarn check

      - name: Test
        run: yarn workspaces foreach --all run test

      - name: Build 🔨
        run: yarn workspaces foreach --from '@munchkin/{cordova,pwa}' --parallel --recursive run build

      - name: Create Sentry release
        uses: getsentry/action-release@ff07929a6537bac57790c3451cf4d364aca38528 # v3.7.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
          release: ${{ format('munchkin@{0}', env.VERSION) }}
          sourcemaps: "./packages/cordova/www ./packages/pwa/dist"

      - name: Deploy 🚀
        uses: FirebaseExtended/action-hosting-deploy@500ac625ca2dd40cbd15f7659af953801858032a # v0.11.0
        with:
          channelId: live
          entryPoint: packages/pwa
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_IZORG_MUNCHKIN }}
          projectId: izorg-munchkin
          repoToken: ${{ secrets.GITHUB_TOKEN }}
